[package]
name = "sad_macros"
version = "0.2.0"
edition = "2021"
description = "Macros for said crate"
license = "EUPL-1.2"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"]}
quote = "1.0"
