[package]
name = "cesrox"
version = "0.1.0"
edition = "2021"
description = "Implementation of Composable Event Streaming Representation (CESR)"
license = "EUPL-1.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
