name: Publish SAID to crates.io

on:
  push:
    tags:
      - "said-v*"
env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: said

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Run clippy
        run: cargo clippy --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all-features --verbose

      - uses: katyo/publish-crates@v1
        with:
            path: './said'
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
            args: '--all-features'
